language: groovy
jdk:
  - openjdk11
sudo: false
branches:
  only:
  - master-nbn-4.1.0
  - develop
  - get-travis-working2
before_install:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish'
env:
  global:
  - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
  - secure: cEhn4RjEiQKPxM3Q/TOiEHStqkxZD1dthChWVgBLiiYq06kobrai6mwpj8jttaceunPPxo3Zy8AFDBVK2iPaSbwvhEx6IkqtL/AcfAzMfi4g44objK3oTywPErn09FiP8Eb6gjJvfcPklABeWjMSmXxxkjhI9w9EU8UcqptRfDxXtOT/vOg/MxMEaTbeVjm6Tc3WVcbvkQ/KpBjqE8prTckJYbBWzhldW+/u/0+ihjAG0sMzLYjun6u1955lfnG3imP2kha8392YArTINFPhF+pWZVvhoOKivtaddIAhwcEefqI3mzsTYR8JT7DW7xXyaZb15/RQ6GRSZRWc/PjefN8qOhh1lqe6fT87Z1Ej6UfsUkg8EETe2HB0hFucI9G+91U2QDp1BQMls1WL5RvEsCInPgrn/xN1KZB8iqHjJbHrN7VXSxgmsAPv+jUZ03Y3vtAOfft+foFb4K2GGdodSDdknLuNK5OzYKJ+K9UPy5CKHTZ7ZtVCyjZCpo/6v3vfC4lSxPTQ3GqBNCLpZmaFw+DliDk07SjV60YpiHgj3aBLg7QuHZ1Nrp7lpzeRNCHam1aef/USb/itx+kXYcQO1sKtcYiBHehqkxRe9hRrJ7R18hkuLDKtscgLqa6cc/HWDEuguyPWZf8FyieSuOzFu6SenOUl3y9z9GJkeq5IXiQ=
  - secure: W79VtwQ6UMbkTfEQlJeuaV8ElVw73EVP82JKi3YSQWFd7s4ltxHZgOvIEX/gXVQ2d5YdhZ3zKBiQPnDVqJ9fgel0Y3ot11SXW/sG5M69fg71FN/K42Vcx8fgt713reZt/sc+tN/yfgv8B1osBXekJaDtC3ZaurysR26vghT2m6daDcsupynWcQ6h/3SEtgF6fbkm6o4nVFvsBDws5Cs3bdsdKe9VcL8NP84PBdtL94/iDDAKcyKMs9vaaXS8Qv3wSyeZZxfqwWQuaXTJSjv5BhQOduyNa/0+Irq9K/n3kLo68CqqIT5sTmrNvvJNjyYUzhtNb2Wom1qBNyJjpiRdopPkvmQS+KCvpWXjh7YpiuNnD43qEJvr1UF+VUvROv05rT8abmgTl+Qk5nb4vsOZuHGCFkASf+3Kcn8IeBpJK9eYLFhYhIthloVbDltxGgNti1wP+RSl4XaQPPTamBlbQClyI8RNmWDOGu+mcWdtyjMl/8cGcBr1BBVLzHDWC9AaOdj4HjKYsX/arJSE33NTcg0sF6IldLk2nG9dIlTrrGM9T3EScIJy4Bn5NVtI0E0n/uaabAuL84goU17jEqOoi86C5E7nk5WbHxqYJ9XZGDMyXXeGaQsZmZw4n6aVDTNnN6Ft4nXJDA2Kr335Pii8TYLocndNJm2ILsjzB+hBiss=
